openapi: 3.0.4
info:
  title: Frame Game API
  description: |-
    API to interact with FrameGame functionality
  version: 0.1.1
servers:
  - url: http://localhost:3000/api
    description: Local dev staging server
  - url: ec2-18-225-195-233.us-east-2.compute.amazonaws.com/api
    description: EC2 test server
tags:
  - name: matchup
    description: Generate matchups with moves
  - name: character
    description: Individual character functions
  - name: move
    description: Individual move data
paths:
  /matchup:
    get:
      tags:
        - matchup
      summary: Generate a matchup
      operationId: getMatchup
      parameters:
        - in: query
          name: game
          schema:
            type: string
          required: true
          description: Dustloop's abbreviation (e.g. "GGST" for Strive) for the game to get a matchup from
          example: "GGST"
      responses:
        '200':
          description: A randomly generated matchup object based on the given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matchup'
              example:
                code: "200"
                content:
                  player1:
                    charName: "Testament"
                    moveData:
                      startup: 8
                      input: "c.S"
                      type: "normal"
                      imagePaths:
                        0: "https://www.dustloop.com/w/Special:FilePath/GGST_Testament_cS.png"
                  player2:
                    charName: "Ky Kiske"
                    moveData:
                      startup: 29
                      input: "236[D]"
                      type: "other"
                      imagePaths:
                        0: "https://www.dustloop.com/w/Special:FilePath/GGST Ky Kiske 236D.png"
        '300':
          description: Bad Request. Check required parameters.
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /character:
    get:
      tags: 
        - character
      summary: Generate a random Player object (character with move) for specified game
      operationID: getPlayer
      parameters:
        - in: query
          name: game
          schema:
            type: string
          required: true
          description: Dustloop's abbreviation (e.g. "GGST" for Strive) for the game to pull a character from
          example: "GGST"
      responses:
        '200':
          description: A randomly generated Player object based on the given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
              example:
                code: "200"
                content:
                  charName: "Testament"
                  moveData:
                    startup: 8
                    input: "c.S"
                    type: "normal"
                    imagePaths:
                      0: "https://www.dustloop.com/w/Special:FilePath/GGST_Testament_cS.png"
        '300':
          description: Bad Request. Check required parameters.
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /move:
    get:
      tags: 
        - move
      summary: Generate a random move for specified game
      operationID: getMove
      parameters:
        - in: query
          name: game
          schema:
            type: string
          required: true
          description: Dustloop's abbreviation (e.g. "GGST" for Strive) for the game to pull a character from
          example: "GGST"
        - in: query
          name: charName
          schema:
            type: string
          required: true
          description: Dustloop's name for the character to pull a move from
          example: "Testament"
      responses:
        '200':
          description: A randomly chosen Move based on the given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Move'
              example:
                code: "200"
                content:
                  startup: 8
                  input: "c.S"
                  type: "normal"
                  imagePaths:
                    0: "https://www.dustloop.com/w/Special:FilePath/GGST_Testament_cS.png"
        '300':
          description: Bad Request. Check required parameters.
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Matchup:
      type: object
      properties:
        player1:
          type: object
          description: Player 1 object
          schema:
            $ref: "#/components/schemas/Player"
        player2:
          type: object
          description: Player 2 object
          schema:
            $ref: "#/components/schemas/Player"
    Player:
      type: object
      properties:
        charName:
          type: string
          description: Name of Player character
        moveData:
          type: object
          description: Data of Player's chosen Move
          schema:
            $ref: "#/components/schemas/Move"
    Move:
      type: object
      properties:
        input: 
          type: string
          description: String representation of the move's input (i.e. 236H)
        type:
          type: string
          description: Type of given move from wiki (e.g. Normal, Special)
        startup:
          type: integer
          description: Number of startup frames for the move
        imagePaths:
          type: array
          items:
            type: string
          description: Array of links to images for move (some moves may have multiple images associated)
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
